/*
Golang version of mendel's accountant....
*/

package main

import (
	// "bytes"
	// "encoding/json"
	"fmt"
	"flag"
	"log"
	"os"
	// "path"
	// "path/filepath"
	// "io"
	// "io/ioutil"
	// "reflect"
	// "strings"
	// "net/http"
	// "runtime"

	// "github.com/davecgh/go-spew/spew"

	// "bitbucket.org/geneticentropy/bucket-brigade/..."
)

// const FOOTER = "# vim: set ts=4 sw=4 expandtab:"

func usage(exitCode int) {
	usageStr1 := `Usage:
  mendel {-c | -f} [filename]
  mendel -d

Perform a mendel run...

Options:
`

	usageStr2 := `
Examples:
  mendel -f /home/bob/mendel.in    # run with this input file
  mendel -d     # run with all default parameters
  mendel -c /home/bob/mendel.in    # create an input file primed with defaults, then you can edit it
`

	if exitCode > 0 {
		fmt.Fprintf(os.Stderr, usageStr1)		// send it to stderr
		flag.PrintDefaults()
		fmt.Fprintf(os.Stderr, usageStr2)		// send it to stderr
	} else {
		fmt.Printf(usageStr1)		// send it to stdout
		flag.PrintDefaults()		//todo: do not yet know how to get this to print to stdout
		fmt.Printf(usageStr2)		// send it to stdout
	}
	os.Exit(exitCode)
}


func main() {
	// Get and check cmd line options
	var inputFile, inputFileToCreate string
	var useDefaults bool
	flag.StringVar(&inputFile, "f", "", "Input file for this mendel run")
	flag.StringVar(&inputFileToCreate, "c", "", "Input file to be generated by mendel")
	flag.BoolVar(&useDefaults, "d", false, "Run mendel with all default parameters")
	flag.Usage = func() { usage(0) }
	flag.Parse()
	// spew.Dump(flag.Lookup("f").Value.String())
	// os.Exit(0)
	// if name == "" && !isStdinFile() { usage(0) }
	if !useDefaults && inputFile == "" && inputFileToCreate == "" { usage(0) }
	if inputFileToCreate != "" {
		if inputFile != "" || useDefaults { log.Printf("Error: if you specify -c you can not specify either -f or -d"); usage(1) }
		log.Printf("Creating input file %v with defaults...", inputFileToCreate)
	} else if useDefaults {
		if inputFile != "" || inputFileToCreate != "" { log.Printf("Error: if you specify -d you can not specify either -f or -c"); usage(1) }
		log.Printf("Running with defaults...")
	} else {
		// they specified the -f flag
		log.Printf("Running with input file %v...", inputFile)

	}
	// can use this to get values anywhere in the program: flag.Lookup("name").Value.String()

	fmt.Println("Running mendel...")

	// log.Fatalf("something really bad went wrong: %v", err)
}
